/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 31
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 27
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_content_token1 = 1,
  anon_sym_LBRACE_LBRACE = 2,
  anon_sym_LBRACE_LBRACE_DASH = 3,
  anon_sym_RBRACE_RBRACE = 4,
  anon_sym_DASH_RBRACE_RBRACE = 5,
  anon_sym_DASH_DASH_DASH = 6,
  anon_sym_PIPE_GT = 7,
  anon_sym_for = 8,
  sym_of_keyword = 9,
  sym_keyword = 10,
  aux_sym_code_snippet_token1 = 11,
  sym_close_keyword = 12,
  sym_comment = 13,
  sym__code = 14,
  sym__front_matter_content = 15,
  sym_template = 16,
  sym_content = 17,
  sym_tag = 18,
  sym_front_matter = 19,
  sym__expression = 20,
  sym_filter = 21,
  sym_for_statement = 22,
  sym_code_snippet = 23,
  aux_sym_template_repeat1 = 24,
  aux_sym_content_repeat1 = 25,
  aux_sym_filter_repeat1 = 26,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_content_token1] = "content_token1",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_LBRACE_LBRACE_DASH] = "{{-",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_DASH_RBRACE_RBRACE] = "-}}",
  [anon_sym_DASH_DASH_DASH] = "---",
  [anon_sym_PIPE_GT] = "|>",
  [anon_sym_for] = "keyword",
  [sym_of_keyword] = "keyword",
  [sym_keyword] = "keyword",
  [aux_sym_code_snippet_token1] = "code_snippet_token1",
  [sym_close_keyword] = "keyword",
  [sym_comment] = "comment",
  [sym__code] = "_code",
  [sym__front_matter_content] = "front_matter_content",
  [sym_template] = "template",
  [sym_content] = "content",
  [sym_tag] = "tag",
  [sym_front_matter] = "front_matter",
  [sym__expression] = "_expression",
  [sym_filter] = "filter",
  [sym_for_statement] = "for_statement",
  [sym_code_snippet] = "code",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_content_repeat1] = "content_repeat1",
  [aux_sym_filter_repeat1] = "filter_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_content_token1] = aux_sym_content_token1,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_LBRACE_LBRACE_DASH] = anon_sym_LBRACE_LBRACE_DASH,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_DASH_RBRACE_RBRACE] = anon_sym_DASH_RBRACE_RBRACE,
  [anon_sym_DASH_DASH_DASH] = anon_sym_DASH_DASH_DASH,
  [anon_sym_PIPE_GT] = anon_sym_PIPE_GT,
  [anon_sym_for] = sym_keyword,
  [sym_of_keyword] = sym_keyword,
  [sym_keyword] = sym_keyword,
  [aux_sym_code_snippet_token1] = aux_sym_code_snippet_token1,
  [sym_close_keyword] = sym_keyword,
  [sym_comment] = sym_comment,
  [sym__code] = sym__code,
  [sym__front_matter_content] = sym__front_matter_content,
  [sym_template] = sym_template,
  [sym_content] = sym_content,
  [sym_tag] = sym_tag,
  [sym_front_matter] = sym_front_matter,
  [sym__expression] = sym__expression,
  [sym_filter] = sym_filter,
  [sym_for_statement] = sym_for_statement,
  [sym_code_snippet] = sym_code_snippet,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
  [aux_sym_filter_repeat1] = aux_sym_filter_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = true,
  },
  [sym_of_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_code_snippet_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_close_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__code] = {
    .visible = false,
    .named = true,
  },
  [sym__front_matter_content] = {
    .visible = true,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_front_matter] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_filter] = {
    .visible = true,
    .named = true,
  },
  [sym_for_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_code_snippet] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_filter_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = sym_code_snippet,
  },
  [2] = {
    [1] = sym_code_snippet,
    [3] = sym_code_snippet,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(75);
      ADVANCE_MAP(
        '#', 72,
        '-', 3,
        '/', 14,
        'd', 94,
        'e', 93,
        'f', 98,
        'i', 96,
        'l', 92,
        'o', 97,
        's', 95,
        '{', 68,
        '|', 5,
        '}', 69,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '!' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == '.' ||
          lookahead == '>' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '#', 72,
        '-', 71,
        '/', 14,
        'd', 94,
        'e', 93,
        'f', 98,
        'i', 96,
        'l', 92,
        's', 95,
        '|', 5,
        '}', 69,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '!' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == '.' ||
          lookahead == '>' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(100);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '}') ADVANCE(70);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(86);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(87);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(63);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(67);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(64);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(31);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(58);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(26);
      if (lookahead == 'x') ADVANCE(50);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(59);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(32);
      END_STATE();
    case 14:
      if (lookahead == 'd') ADVANCE(20);
      if (lookahead == 'e') ADVANCE(11);
      if (lookahead == 'f') ADVANCE(41);
      if (lookahead == 'i') ADVANCE(22);
      if (lookahead == 'l') ADVANCE(7);
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(17);
      END_STATE();
    case 16:
      if (lookahead == 'd') ADVANCE(18);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(90);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(57);
      if (lookahead == 'l') ADVANCE(43);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 21:
      if (lookahead == 'f') ADVANCE(89);
      END_STATE();
    case 22:
      if (lookahead == 'f') ADVANCE(99);
      if (lookahead == 'm') ADVANCE(50);
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 23:
      if (lookahead == 'f') ADVANCE(6);
      END_STATE();
    case 24:
      if (lookahead == 'f') ADVANCE(8);
      END_STATE();
    case 25:
      if (lookahead == 'h') ADVANCE(37);
      END_STATE();
    case 26:
      if (lookahead == 'h') ADVANCE(39);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(42);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(45);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(56);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(57);
      END_STATE();
    case 31:
      if (lookahead == 'l') ADVANCE(61);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(65);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(90);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(99);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 37:
      if (lookahead == 'o') ADVANCE(90);
      END_STATE();
    case 38:
      if (lookahead == 'o') ADVANCE(56);
      END_STATE();
    case 39:
      if (lookahead == 'o') ADVANCE(99);
      END_STATE();
    case 40:
      if (lookahead == 'o') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(40);
      END_STATE();
    case 41:
      if (lookahead == 'o') ADVANCE(52);
      if (lookahead == 'u') ADVANCE(36);
      END_STATE();
    case 42:
      if (lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 43:
      if (lookahead == 'o') ADVANCE(57);
      END_STATE();
    case 44:
      if (lookahead == 'o') ADVANCE(51);
      END_STATE();
    case 45:
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 46:
      if (lookahead == 'o') ADVANCE(60);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(54);
      END_STATE();
    case 48:
      if (lookahead == 'o') ADVANCE(62);
      END_STATE();
    case 49:
      if (lookahead == 'p') ADVANCE(44);
      END_STATE();
    case 50:
      if (lookahead == 'p') ADVANCE(47);
      END_STATE();
    case 51:
      if (lookahead == 'r') ADVANCE(56);
      END_STATE();
    case 52:
      if (lookahead == 'r') ADVANCE(99);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(88);
      END_STATE();
    case 54:
      if (lookahead == 'r') ADVANCE(57);
      END_STATE();
    case 55:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 56:
      if (lookahead == 't') ADVANCE(90);
      END_STATE();
    case 57:
      if (lookahead == 't') ADVANCE(99);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 59:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 60:
      if (lookahead == 'u') ADVANCE(56);
      END_STATE();
    case 61:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 62:
      if (lookahead == 'u') ADVANCE(57);
      END_STATE();
    case 63:
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 64:
      if (lookahead == 'u') ADVANCE(30);
      END_STATE();
    case 65:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 66:
      if (lookahead == 'y') ADVANCE(46);
      END_STATE();
    case 67:
      if (lookahead == 'y') ADVANCE(48);
      END_STATE();
    case 68:
      if (lookahead == '{') ADVANCE(82);
      END_STATE();
    case 69:
      if (lookahead == '}') ADVANCE(84);
      END_STATE();
    case 70:
      if (lookahead == '}') ADVANCE(85);
      END_STATE();
    case 71:
      if (lookahead == '}') ADVANCE(70);
      END_STATE();
    case 72:
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(2);
      END_STATE();
    case 73:
      if (eof) ADVANCE(75);
      if (lookahead == '-') ADVANCE(78);
      if (lookahead == '{') ADVANCE(79);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0) ADVANCE(81);
      END_STATE();
    case 74:
      if (eof) ADVANCE(75);
      if (lookahead == '{') ADVANCE(79);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(80);
      if (lookahead != 0) ADVANCE(81);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '-') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(81);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '-') ADVANCE(78);
      if (lookahead == '{') ADVANCE(79);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0) ADVANCE(81);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '-') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(81);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '{') ADVANCE(82);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '{') ADVANCE(79);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(80);
      if (lookahead != 0) ADVANCE(81);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead == '-') ADVANCE(83);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_DASH);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_DASH_RBRACE_RBRACE);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_DASH);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_PIPE_GT);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_of_keyword);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_keyword);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_code_snippet_token1);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_code_snippet_token1);
      if (lookahead == 'a') ADVANCE(66);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_code_snippet_token1);
      if (lookahead == 'c') ADVANCE(25);
      if (lookahead == 'l') ADVANCE(55);
      if (lookahead == 'x') ADVANCE(49);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_code_snippet_token1);
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_code_snippet_token1);
      if (lookahead == 'e') ADVANCE(56);
      if (lookahead == 'l') ADVANCE(38);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_code_snippet_token1);
      if (lookahead == 'f') ADVANCE(90);
      if (lookahead == 'm') ADVANCE(49);
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_code_snippet_token1);
      if (lookahead == 'f') ADVANCE(89);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_code_snippet_token1);
      if (lookahead == 'o') ADVANCE(53);
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_close_keyword);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 73},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 74},
  [4] = {.lex_state = 74},
  [5] = {.lex_state = 74},
  [6] = {.lex_state = 74},
  [7] = {.lex_state = 74},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 74},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 74},
  [12] = {.lex_state = 0, .external_lex_state = 2},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 74},
  [16] = {.lex_state = 74},
  [17] = {.lex_state = 74},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 3},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 40},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0, .external_lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_DASH_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(1),
    [anon_sym_PIPE_GT] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [sym_of_keyword] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [aux_sym_code_snippet_token1] = ACTIONS(1),
    [sym_close_keyword] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__code] = ACTIONS(1),
    [sym__front_matter_content] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_template] = STATE(27),
    [sym_content] = STATE(3),
    [sym_tag] = STATE(3),
    [sym_front_matter] = STATE(4),
    [aux_sym_template_repeat1] = STATE(3),
    [aux_sym_content_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_content_token1] = ACTIONS(5),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(7),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(13), 1,
      anon_sym_PIPE_GT,
    ACTIONS(15), 1,
      anon_sym_for,
    ACTIONS(17), 1,
      sym_keyword,
    ACTIONS(19), 1,
      aux_sym_code_snippet_token1,
    STATE(14), 1,
      aux_sym_filter_repeat1,
    STATE(22), 1,
      sym_filter,
    ACTIONS(11), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
    ACTIONS(21), 2,
      sym_close_keyword,
      sym_comment,
    STATE(8), 3,
      sym__expression,
      sym_for_statement,
      sym_code_snippet,
  [32] = 5,
    ACTIONS(5), 1,
      aux_sym_content_token1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      aux_sym_content_repeat1,
    ACTIONS(7), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
    STATE(6), 3,
      sym_content,
      sym_tag,
      aux_sym_template_repeat1,
  [51] = 5,
    ACTIONS(5), 1,
      aux_sym_content_token1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      aux_sym_content_repeat1,
    ACTIONS(7), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
    STATE(5), 3,
      sym_content,
      sym_tag,
      aux_sym_template_repeat1,
  [70] = 5,
    ACTIONS(5), 1,
      aux_sym_content_token1,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      aux_sym_content_repeat1,
    ACTIONS(7), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
    STATE(6), 3,
      sym_content,
      sym_tag,
      aux_sym_template_repeat1,
  [89] = 5,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      aux_sym_content_token1,
    STATE(7), 1,
      aux_sym_content_repeat1,
    ACTIONS(32), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
    STATE(6), 3,
      sym_content,
      sym_tag,
      aux_sym_template_repeat1,
  [108] = 4,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      aux_sym_content_token1,
    STATE(9), 1,
      aux_sym_content_repeat1,
    ACTIONS(39), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
  [122] = 4,
    ACTIONS(13), 1,
      anon_sym_PIPE_GT,
    STATE(14), 1,
      aux_sym_filter_repeat1,
    STATE(23), 1,
      sym_filter,
    ACTIONS(41), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
  [136] = 4,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 1,
      aux_sym_content_token1,
    STATE(9), 1,
      aux_sym_content_repeat1,
    ACTIONS(48), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
  [150] = 2,
    ACTIONS(52), 1,
      sym__code,
    ACTIONS(50), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PIPE_GT,
  [159] = 2,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    ACTIONS(56), 3,
      aux_sym_content_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
  [168] = 2,
    ACTIONS(60), 1,
      sym__code,
    ACTIONS(58), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PIPE_GT,
  [177] = 3,
    ACTIONS(64), 1,
      anon_sym_PIPE_GT,
    STATE(13), 1,
      aux_sym_filter_repeat1,
    ACTIONS(62), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
  [188] = 3,
    ACTIONS(13), 1,
      anon_sym_PIPE_GT,
    STATE(13), 1,
      aux_sym_filter_repeat1,
    ACTIONS(67), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
  [199] = 2,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(71), 3,
      aux_sym_content_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
  [208] = 2,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 3,
      aux_sym_content_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
  [217] = 2,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 3,
      aux_sym_content_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
  [226] = 1,
    ACTIONS(81), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PIPE_GT,
  [232] = 1,
    ACTIONS(83), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PIPE_GT,
  [238] = 1,
    ACTIONS(85), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PIPE_GT,
  [244] = 1,
    ACTIONS(87), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PIPE_GT,
  [250] = 1,
    ACTIONS(41), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
  [255] = 1,
    ACTIONS(89), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
  [260] = 1,
    ACTIONS(91), 1,
      sym__code,
  [264] = 1,
    ACTIONS(93), 1,
      sym__code,
  [268] = 1,
    ACTIONS(95), 1,
      sym__front_matter_content,
  [272] = 1,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
  [276] = 1,
    ACTIONS(99), 1,
      sym_of_keyword,
  [280] = 1,
    ACTIONS(101), 1,
      anon_sym_DASH_DASH_DASH,
  [284] = 1,
    ACTIONS(103), 1,
      sym__code,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 32,
  [SMALL_STATE(4)] = 51,
  [SMALL_STATE(5)] = 70,
  [SMALL_STATE(6)] = 89,
  [SMALL_STATE(7)] = 108,
  [SMALL_STATE(8)] = 122,
  [SMALL_STATE(9)] = 136,
  [SMALL_STATE(10)] = 150,
  [SMALL_STATE(11)] = 159,
  [SMALL_STATE(12)] = 168,
  [SMALL_STATE(13)] = 177,
  [SMALL_STATE(14)] = 188,
  [SMALL_STATE(15)] = 199,
  [SMALL_STATE(16)] = 208,
  [SMALL_STATE(17)] = 217,
  [SMALL_STATE(18)] = 226,
  [SMALL_STATE(19)] = 232,
  [SMALL_STATE(20)] = 238,
  [SMALL_STATE(21)] = 244,
  [SMALL_STATE(22)] = 250,
  [SMALL_STATE(23)] = 255,
  [SMALL_STATE(24)] = 260,
  [SMALL_STATE(25)] = 264,
  [SMALL_STATE(26)] = 268,
  [SMALL_STATE(27)] = 272,
  [SMALL_STATE(28)] = 276,
  [SMALL_STATE(29)] = 280,
  [SMALL_STATE(30)] = 284,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_snippet, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_filter_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_filter_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_front_matter, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_front_matter, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_snippet, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 2, 0, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_filter_repeat1, 2, 0, 1),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 4, 0, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [97] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__code = 0,
  ts_external_token__front_matter_content = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__code] = sym__code,
  [ts_external_token__front_matter_content] = sym__front_matter_content,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__code] = true,
    [ts_external_token__front_matter_content] = true,
  },
  [2] = {
    [ts_external_token__code] = true,
  },
  [3] = {
    [ts_external_token__front_matter_content] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_vento_external_scanner_create(void);
void tree_sitter_vento_external_scanner_destroy(void *);
bool tree_sitter_vento_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_vento_external_scanner_serialize(void *, char *);
void tree_sitter_vento_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_vento(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_vento_external_scanner_create,
      tree_sitter_vento_external_scanner_destroy,
      tree_sitter_vento_external_scanner_scan,
      tree_sitter_vento_external_scanner_serialize,
      tree_sitter_vento_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "vento",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 21,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
